class NoneException(Exception):
    def __init__(self, message="Erro ao recuperar valor do d√≥lar!."):
        super().__init__(message)
